rvm:
  - 2.0.0
  - 2.1.0
before_script:
    - bundle exec berks install
bundler_args: --without integration
script:
  - bundle exec foodcritic -f any .
  - bundle exec rubocop
  - bundle exec knife cookbook test
